# Generated by Django 2.1.15 on 2023-04-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_contract_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Dublin 1', 'Dublin 1'), ('Dublin 2', 'Dublin 2'), ('Cork', 'Cork'), ('Galway', 'Galway')], max_length=50),
        ),
    ]
